### ISSUE TITLE
Part ID mismatch between source and content

### ISSUE THREAD

**Issue by tuckerzp** [usnistgov/oscal-content#117]
In reference to an issue found at https://github.com/EasyDynamics/oscal-react-library/pull/485#issuecomment-1178468795.

There seems to be a discrepancy between the **NIST 800-53 Rev 5** [source catalog](https://raw.githubusercontent.com/usnistgov/oscal-content/main/src/nist.gov/SP800-53/rev5/xml/NIST_SP-800-53_rev5_catalog.xml) and the [`json`](https://raw.githubusercontent.com/usnistgov/oscal-content/b97d0c0f682d6686c64077678f5e409427972f23/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json), [`xml`](https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/xml/NIST_SP-800-53_rev5_catalog.xml), & [`yaml`](https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/yaml/NIST_SP-800-53_rev5_catalog.yaml) representations in `/content`. The part id's that are originally shown as `ac-1_obj.a-1` & `ac-1_obj.a.1` in `/src` are both shown as `ac-1_obj.a.1` in `/content`. This seems to be a common change with many other part id's. Because this leads to a duplication of `part.id`, I wanted to know if there was another way to discern the two parts other than their id.

**Comment by aj-stein-nist** [comment]
Hey @tuckerzp, thank you so much for reporting this. During a triage meeting we dove deep into this, and you helped surface to us a subtle little CI/CD bug, so updated content is not being propagated from `/src` to `/content` as reported. Sit tight, a fix will be incoming.

**Comment by aj-stein-nist** [comment]
@tuckerzp, sorry for the delays, just a quick update since you reported and it was connected to an issue in your library. We merged the CI/CD code, but we had to relax the review and branch protection configuration and re-run CI/CD to actually process the content correctly. Things should look good and clean now on `main` as of https://github.com/usnistgov/oscal-content/commit/159073e8a8ca16b3f8fba695aa00018f12535719 after we debugged that. Should be completely good after that landed.
