### ISSUE TITLE
Corrections to SP800-53 Rev5 OSCAL with associated patches to its production pipeline

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/oscal-content#15]
# Describe the bug

Several errors have been found in the version of the SP800-53 Rev 5 FPD now distributed on the OSCAL site here: https://github.com/usnistgov/OSCAL/blob/master/src/content/nist.gov/SP800-53/rev5/xml/NIST_SP-800-53_rev5-FPD_catalog.xml

These errors are then propagated (in CI/CD) to released XML and JSON versions in the `content` directory.

Here are the issues we know of so far:

- [ ] AU-9 (7) missing "Related" links
- [ ] SA-11 (2) missing "Related" links
- [ ] PT-8 (2) - requires inline link to resource [PRIVACT] in Guidance section
- [ ] IA-5 (2) PUBLIC KEY-BASED AUTHENTICATION - the actual title is dropped, with the statement appearing as the title and the guidance ("Discussion") appearing as the statement
- [ ] MA-4 (4) - missing guidance (Discussion) part

# Who is the bug affecting?

*Anybody* who needs to rely on this data.

# What is affected by this bug?

*Any* downstream processing of these controls (enhancements).

# Expected behavior (i.e. solution)

The conversion pipeline must be amended to correct these errors. This may require changes in either or both the source->NVD-XML extraction, or the NVD-XML to OSCAL conversion. Where the extraction cannot be corrected due to anomalies in the source data, the conversion step can be provided with a patch to insert the corrected information.

**Comment by wendellpiez** [comment]
@david-waltermire-nist Nope, this is our placeholder ticket. We have not yet determined which of these might be corrected in the source, vs which ones warrant patches in the conversion. For actual errors not just small representational glitches, presumably corrections upstream will be wanted. (As you can see the FISMA team was in the loop when these were first brought up as well.)

**Comment by iMichaela** [comment]
## 9/23/2020 - conversion review of 800-53 rev5 (final)

 - [ ] all inline references are missing the links
 - [ ] all controls mentioned in the guidance/discussion are missing the links.  What is the appropriate rel for this type of controls mentioned in the discussion?
- [ ] AU-9 (7) missing "Related controls: links for AU-4, AU-5, AU-11, SC-29 [line 4412] due to lower case 'controls' in "related controls" in the original document.
 - [ ] PM-30 guidance/discussion missing inline link [line 14706]
  - [ ] PT-8 (2) - requires inline link to resource [PRIVACT] in Guidance section [line 15977]
  - [ ] RA-2 guidance/discussion needs inline link to resource [CNSSI 1253] , [USA PATRIOT] and  and CM-8 [lines 16105 - 16107]
 - [ ] RA-2 (1) missing inline link to resources [FIPS 199]
 - [ ]  SA-11 (2) missing "Related controls" links for PM-15, RA-3, RA-5 [line: 18360]  due to lower case 'controls' in "related controls" in the original document.
  - [ ] IA-5 (2) PUBLIC KEY-BASED AUTHENTICATION - the actual title is dropped, and a large part of th econtent is missing I guess because it starts with bullets without any leading text, IA-5(2)(b)(2) becomes the title and the guidance ("Discussion") appearing as the statement [line 9090]
  - [ ] MA-4 (4) - missing MA-4 (4) (b)(2) and the guidance (Discussion) part . content missing after [line 10993]

@david-waltermire-nist and @wendellpiez - some of the errors listed above can be corrected manually, but others are more generic and would be better to be corrected up the stream, if possible.

**Comment by wendellpiez** [comment]
My current plan is to break these into three:

1.	Easy repairs to conversion pipeline
2.	Easy patches to add to pipeline
3.	Hand repairs remaining

Then I will start working through them, starting with 1.

In this meeting we can review my progress and plan the further work.

Note that maintaining the NVD-production pipeline as a dependency for the OSCAL production pipeline is _no longer_ a goal, so we do not have the option of enhancing or correcting NVD production output to improve the data.

**Comment by wendellpiez** [comment]
The listing below is reordered from the comment above, which I will check as addressed (since they are here).

### Pipeline enhancements

- [ ]  all inline references are missing the links - *we have never had links before (there were fewer) and NVD does not capture inline links; however they could be restored with a filter (see below)*
- [ ]  all controls mentioned in the guidance/discussion are missing the links. What is the appropriate rel for this type of controls mentioned in the discussion? *probably simple cross-links (anchor tags) tagged by the same enhancement filter*
- [ ]  PT-8 (2) - requires inline link to resource [PRIVACT] in Guidance section [line 15977]
- [ ]  RA-2 guidance/discussion needs inline link to resource [CNSSI 1253] , [USA PATRIOT] and and CM-8 [lines 16105 - 16107]
- [ ]  RA-2 (1) missing inline link to resources [FIPS 199]

As noted, this would be a new feature. Fortunately these can all be addressed by a filter that will provide links when it sees a link target literal inside `p` (the only prose element being used). We can take any substring (such as `[PRIVACT]` that corresponds to an internal link target (literal), i.e. a `resource/title` -- or `control/prop[@name='label']` as a link.

### Patches

- [ ]  AU-9 (7) missing "Related controls: links for AU-4, AU-5, AU-11, SC-29 [line 4412] due to lower case 'controls' in "related controls" in the original document. *suggest patch*
- [ ]  PM-30 guidance/discussion missing inline link [line 14706] *assuming the linker filter does not capture this it can be patched or done by hand*
- [ ]  SA-11 (2) missing "Related controls" links for PM-15, RA-3, RA-5 [line: 18360] due to lower case 'controls' in "related controls" in the original document.
- [ ]  IA-5 (2) PUBLIC KEY-BASED AUTHENTICATION - the actual title is dropped, and a large part of th econtent is missing I guess because it starts with bullets without any leading text, IA-5(2)(b)(2) becomes the title and the guidance ("Discussion") appearing as the statement [line 9090]
- [ ]  MA-4 (4) - missing MA-4 (4) (b)(2) and the guidance (Discussion) part . content missing after [line 10993]

These appear to be due to anomalies in the input, and probably reflect defects in the NVD XML intermediate. Patching is appropriate.

### Hand fixes

Since we have to code the missing pieces by hand anyhow, we may as well install as patches.

**Comment by iMichaela** [comment]
@david-waltermire-nist and @wendellpiez - it appears that the following missing content:

 [ ] MA-4 (4) - missing MA-4 (4) (b)(2) and the guidance (Discussion) part . content missing after [line 10993]

could be caused by a missing rule in the NVD pipeline.
![image](https://user-images.githubusercontent.com/13984545/94202092-0110aa00-fe8b-11ea-9fc8-b14985d431a5.png)

There is only one instance in the entire 800-53r5 with the above structure: a number-based lists (as opose to letter-based list) with the line above ending in "; or"

**Comment by wendellpiez** [comment]
@iMichaela I am sending a file with hand patches for you to compare with the earlier.

**Comment by iMichaela** [comment]
@wendell - will review tonight.

**Comment by david-waltermire-nist** [comment]
This was addressed with the merge or PR #32.
