### ISSUE TITLE
Non-Standard/Non-ASCII Characters present in content  (Unless Unicode is intentional?)

### ISSUE THREAD

**Issue by ctraftoncodes** [usnistgov/oscal-content#233]
# Describe the bug

There is an ambiguous character and some Unicode, non-ASCII in some of the prose and content of the data. This makes automation a little bit difficult because unless special checks are put in, this character is ambiguous and renders poorly in word when automatically generated with code - generally, systems use ASCII by default as far as I know.

Here is an example:
![image](https://github.com/usnistgov/oscal-content/assets/75496244/f21e8d30-a957-4cbb-abde-3122d556e5c7)

There are also some other non-standard ASCII Characters present in the content, such as the EM dash. For automation to work best, it is my suggestion to only use standard ASCII characters. In this case, use the regular dash rather than EM Dash and curly quote:

<img width="462" alt="image" src="https://github.com/usnistgov/oscal-content/assets/75496244/3d3a1fe8-f661-473c-88c3-5a38e514b527">

<img width="202" alt="image" src="https://github.com/usnistgov/oscal-content/assets/75496244/30d7f804-947c-436e-b39a-07cbfe027664">

This is unicode, but not ASCII: https://en.wikipedia.org/wiki/Dash#Em_dash

Another one is the non-standard quote:

# Who is the bug affecting?

My team, or anyone who may want to automate without special checks.

# What is affected by this bug?

When rendered on Word via automation, it shows "???" instead of the character.

# When does this occur?

When automatically generated.

# How do we replicate the issue?

you can view it if opening the content in Visual Studio code to see the ambiguous character. 

{What are the steps to reproduce the behavior?

 Open it in VS Code and you will see the warning. Hard to replicate since we have code that places the content in word without special checks in C#.

# Expected behavior (i.e. solution)

no ambiguous characters in the content

# Other Comments

This is a very small, lo-pri issue but worth mentioning since I know there is a push for automation. Please feel free to reach out for any further questions. We wanted to bring it up to make sure we are contributing to the push for automation. We use automation to generate our SSPs.

Also. if we should be ensuring that our automation can handle Unicode, let us know if that was an intentional choice.

**Comment by wendellpiez** [comment]
Yes this was an intentional choice. Happy to discuss further and why this is best for us.

Speaking as a lone dev, in 2024 I think that you should indeed be handling UTF-8, as most commodity tooling does today. Or be prepared to normalize data at the boundaries, as is not uncommon.

(Indeed the more I think about finding an acceptable alternative to UTF-8 or UTF-16 today the more I am glad we don't have to. This is not the no-brainer topic it might seem to be. At the same time I am sympathetic -- all this could have been avoided by data creators, but wasn't. Writers like their punctuation, I guess.)

**Comment by sarnold** [comment]
Just to a third wheel (opinion) I would probably recommend against the more exotic chars in source code and *leave that for the rendering step*.  I normally get to wear both author and engineering hats and I'd much prefer the standard ascii/utf8 chars for sources and let the tools do the rest.  In that vein I can't think of a compelling reason to use the fancy dash/quote bits in a source file, which *will* break something sooner or later.  That said, I'm all about workflow automation so *thank you* for this repo!

**Comment by iMichaela** [comment]
@sarnold and @ctraftoncodes - The content captured in the catalog was created and it is maintained by the RMF team. It has been reviewed and approved by many authoritative entities. We only formatted it in OSCAL and are not allowed to change it since we did not authored it.  If you find any issue with the OSCAL representation and see ways of improving it, please let us know.

**Comment by iMichaela** [comment]
This is not an OSCAL bug, and not something we can change.

**Comment by wendellpiez** [comment]
@imichaela I think the suggestion was not that we change the data, but instead publish not in UTF-8 (as currently) but rather in the subset aligned with ASCII (and thus, for practical purposes, in ASCII). We could do this using standard mechanisms such as (most straightforwardly) [character references](https://www.w3.org/TR/REC-xml/#sec-references), so that in the source, for example, an [em dash character](https://www.fileformat.info/info/unicode/char/2014/index.htm) is encoded as `&#x2014;`.

This is less legible in the source code (to you and me, looking at displays that support UTF-8 such as our web browsers), but also less likely to be mangled, while its representation of Unicode is still unambiguous, supporting correct rendition. (Developers are familiar with this convention from HTML.)

The reason this wasn't done in the current distribution is largely for parity with the JSON publication, which doesn't support this form of escaping. One less source of deltas in diffs.

And also because the transcoding to get it from the current UTF-8 into ASCII is a one-liner in most XML tools, as it relies on a standard feature. So we imagined that users who need the data in 'lower ASCII' also have ways to make that and go from there.

*Hint*: look for an `encoding='ascii'` serialization setting in many XML processors that write out XML, and you are about there. This includes XSLT (all versions) via `xsl:output` along with XQuery engines. A transformation that effects this change (only) is an 'identity transformation' since the data is 'the same' when processed as XML (only the serialization is different).

Here the question was couched as "is this intentional" to which the answer is (more or less) yes. @ctraftoncodes or other readers should certainly feel free to comment or reopen if you think on balance we are wrong.

For now our advice remains: use conformant tools, in this case XML processors that parse utf-8 - and maybe can write out ASCII for you, to produce input ready for that other tool you have, that doesn't know utf-8 or XML....

**Comment by wendellpiez** [comment]
Some deeper background for those not read into fine points of XML:

- XML parsers for conformance must be able to read (parse) data in utf-8 or utf-16 encodings, both of which support Unicode.
- Since utf-8 in particular is a superset of ASCII, an ASCII file can be parsed by a utf-8-capable parser unambiguously.
- But XML processors are *permitted* to recognize and parse any character encoding at all, assuming they provide transcoding support (for Unicode) - the `encoding` pseudo-attribute inside an XML declaration is described to support this. `<?xml version="1.0" encoding="ascii"?>`.
- Partly In order to help support the transcoding this envisions, the XML Recommendation (linked above) describes other ways of including data besides as character literals in the chosen encoding. Character entities is one of these - any character can also be escaped - so `A' is also `&#65;` in XML (try it!). With a little help from them, "all of XML" (all Unicode) can be written out into ASCII.
- This is not the same as transliterating the character, for example rewriting the em (long) dash into '--'. (This is sometimes used as a mitigation for such problems.) It is better because it is both more general, and reversible. But a failed system might display `&#2012;` because it doesn't know. (Or maybe you've seen `&amp;`s in your feeds: same problem.)
- A system that can't handle utf-8 might not be able to handle the character escapes either. Whether you actually see an em dash still depends on what happens down the line.

**Comment by iMichaela** [comment]
@wendellpiez - I think turning your explanation into an ADR might be very useful in the future.
